/**
 * demos/capture-tsc.mjs — real compiler output, captured so a slide can show it.
 *
 *   node weeks/week-12-typescript-mock-surgery/demos/capture-tsc.mjs
 *   node weeks/week-12-typescript-mock-surgery/demos/capture-tsc.mjs --check
 *
 * WHY THIS EXISTS
 *
 * §9.3 says a demo must COMPUTE its claim rather than assert it, and every other week
 * obeys that by running the thing in the slide. This week cannot: `tsc` does not run in
 * a browser, and a hand-typed "error TS2322: …" on a slide is exactly the kind of
 * plausible-looking fiction the course spends twelve weeks teaching students to distrust.
 *
 * So the claim is computed HERE, on this machine, over the real .ts files in
 * `tsc-cases/`, and the result is written to `tsc-output.json` for the demos to load.
 * Every compiler message shown in this week's deck came out of the compiler.
 *
 * `--check` re-runs the capture and fails if it differs from what is on disk, so a case
 * that is edited without re-capturing is caught. tools/test/week-12-demos.test.mjs runs
 * it in that mode.
 *
 * The cases are compiled with the SAME options as the class assignment's tsconfig
 * (strict, ES2022, DOM) so what a student sees in their editor is what the slide shows.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, '..', '..', '..');
const CASES = path.join(HERE, 'tsc-cases');
const OUT = path.join(HERE, 'tsc-output.json');
const check = process.argv.includes('--check');

const TSC = path.join(REPO_ROOT, 'node_modules', '.bin', 'tsc');

/* The class assignment's options, spelled out on the command line so no tsconfig has to
   sit inside the cases folder and get picked up by anything else. */
const OPTIONS = [
  '--noEmit',
  '--strict',
  '--target',
  'ES2022',
  '--module',
  'ES2022',
  '--moduleResolution',
  'bundler',
  '--lib',
  'ES2022,DOM,DOM.Iterable',
  '--pretty',
  'false',
];

const files = (await readdir(CASES)).filter((n) => n.endsWith('.ts')).sort();
if (files.length === 0) {
  console.error('  x no .ts cases found in tsc-cases/');
  process.exit(1);
}

const captured = {};

for (const name of files) {
  const abs = path.join(CASES, name);
  const source = await readFile(abs, 'utf8');
  const r = spawnSync(TSC, [...OPTIONS, abs], { encoding: 'utf8', cwd: CASES });
  const raw = `${r.stdout ?? ''}${r.stderr ?? ''}`;

  /*
   * One entry per diagnostic, with the absolute path stripped — the slide shows a file
   * name, and an absolute path from somebody's laptop is noise that also changes between
   * machines and would make --check fail for no reason.
   */
  const messages = raw
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => /error TS\d+/.test(line))
    .map((line) => {
      const m = /^(.*?)\((\d+),(\d+)\):\s*error\s+(TS\d+):\s*(.*)$/.exec(line);
      if (!m) return { line: 0, column: 0, code: '', text: line };
      return {
        line: Number(m[2]),
        column: Number(m[3]),
        code: m[4],
        text: m[5],
      };
    });

  captured[name] = { source: source.trimEnd(), messages };
}

const payload = {
  '//': 'GENERATED by demos/capture-tsc.mjs. Do not edit. Every message here came out of tsc.',
  tscVersion: (spawnSync(TSC, ['--version'], { encoding: 'utf8' }).stdout ?? '').trim(),
  options: OPTIONS.join(' '),
  cases: captured,
};
const text = `${JSON.stringify(payload, null, 2)}\n`;

if (check) {
  const existing = await readFile(OUT, 'utf8').catch(() => null);
  if (existing === text) {
    const total = Object.values(captured).reduce((n, c) => n + c.messages.length, 0);
    console.log(`  ok  tsc-output.json is current — ${files.length} cases, ${total} diagnostics`);
    process.exit(0);
  }
  console.error('\n  x tsc-output.json is STALE. A case changed and was not re-captured.');
  console.error('    Run: node weeks/week-12-typescript-mock-surgery/demos/capture-tsc.mjs\n');
  process.exit(1);
}

await writeFile(OUT, text, 'utf8');
console.log(`\n  captured ${files.length} cases with ${payload.tscVersion}\n`);
for (const [name, entry] of Object.entries(captured)) {
  console.log(`    ${name.padEnd(28)} ${entry.messages.length} diagnostic(s)`);
  for (const m of entry.messages)
    console.log(`      line ${m.line}  ${m.code}  ${m.text.slice(0, 80)}`);
}
console.log(`\n  ok  ${path.relative(REPO_ROOT, OUT)}\n`);
